#!/bin/bash
# SBATCH --time=1:20:00
sbatch 2ClassSet31finalAttentionsQVK1.sh
sbatch 8ClassSet34finalAttentionsQVK1.sh
sbatch 4ClassSet36finalAttentionsQVK1.sh
sbatch 8ClassSet32finalAttentionsQVK1.sh
sbatch 2ClassSet31finalAttentionsQVK.sh
sbatch 6ClassSet36finalAttentionsQVK1.sh
sbatch 4ClassSet31finalAttentionsQVK1.sh
sbatch 8ClassSet35finalAttentionsQVK1.sh
sbatch 2ClassSet36finalAttentionsQVK1.sh
sbatch 8ClassSet33finalAttentionsQVK1.sh
sbatch 6ClassSet31finalAttentionsQVK1.sh
sbatch 4ClassSet34finalAttentionsQVK1.sh
sbatch 2ClassSet35finalAttentionsQVK1.sh
sbatch 2ClassSet33finalAttentionsQVK1.sh
sbatch 8ClassSet36finalAttentionsQVK1.sh
sbatch 4ClassSet32finalAttentionsQVK1.sh
sbatch 6ClassSet32finalAttentionsQVK1.sh
sbatch 6ClassSet34finalAttentionsQVK1.sh
sbatch 2ClassSet34finalAttentionsQVK1.sh
sbatch 8ClassSet31finalAttentionsQVK1.sh
sbatch 4ClassSet35finalAttentionsQVK1.sh
sbatch 4ClassSet33finalAttentionsQVK1.sh
sbatch 2ClassSet32finalAttentionsQVK1.sh
sbatch 6ClassSet33finalAttentionsQVK1.sh
sbatch 6ClassSet35finalAttentionsQVK1.sh
