#!/bin/bash
# SBATCH --time=1:20:00
sbatch 6ClassSet36finalAttentionsAdv1.sh
sbatch 4ClassSet36finalAttentionsAdv1.sh
sbatch 8ClassSet32finalAttentionsAdv1.sh
sbatch 8ClassSet34finalAttentionsAdv1.sh
sbatch 2ClassSet31finalAttentionsAdv1.sh
sbatch 2ClassSet31finalAttentionsAdv.sh
sbatch 6ClassSet31finalAttentionsAdv1.sh
sbatch 8ClassSet33finalAttentionsAdv1.sh
sbatch 2ClassSet36finalAttentionsAdv1.sh
sbatch 4ClassSet31finalAttentionsAdv1.sh
sbatch 8ClassSet35finalAttentionsAdv1.sh
sbatch 6ClassSet34finalAttentionsAdv1.sh
sbatch 6ClassSet32finalAttentionsAdv1.sh
sbatch 8ClassSet36finalAttentionsAdv1.sh
sbatch 4ClassSet32finalAttentionsAdv1.sh
sbatch 2ClassSet33finalAttentionsAdv1.sh
sbatch 2ClassSet35finalAttentionsAdv1.sh
sbatch 4ClassSet34finalAttentionsAdv1.sh
sbatch 6ClassSet35finalAttentionsAdv1.sh
sbatch 6ClassSet33finalAttentionsAdv1.sh
sbatch 2ClassSet32finalAttentionsAdv1.sh
sbatch 4ClassSet33finalAttentionsAdv1.sh
sbatch 8ClassSet31finalAttentionsAdv1.sh
sbatch 4ClassSet35finalAttentionsAdv1.sh
sbatch 2ClassSet34finalAttentionsAdv1.sh
